version: '3.8'
services:
  nest-api:
    container_name: nest-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3001:3000'
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: mysql
    restart: always
    user: root
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    env_file:
      - .env
